CREATE DATABASE museos;
USE museos;
SELECT *FROM user;
DROP DATABASE museos;


CREATE TABLE USER (
ID_USER 	INT  AUTO_INCREMENT PRIMARY KEY, 
NAME 		VARCHAR(100) NOT NULL, 
F_LAST_NAME 	VARCHAR(50) NOT NULL, 
S_LAST_NAME	VARCHAR(50) NOT NULL, 
PHOTO 		BLOB,
EMAIL		VARCHAR(255) UNIQUE NOT NULL, 
PASSWORD 	VARCHAR(255)     NOT NULL,
ROL             ENUM('usuario','administrador') DEFAULT 'usuario',
ID_GOOGLE	VARCHAR(255) /*id */

);


CREATE TABLE ARTIST(
ID_ARTIST 		INT AUTO_INCREMENT PRIMARY KEY, 
ARTISTIC_NAME 		VARCHAR (100) NOT NULL, 
CELL			INT(10) NOT NULL,
ID_User                 INT,
ID_TYPE                  INT,
FOREIGN KEY (ID_USER)  REFERENCES USER(ID_USER), 
FOREIGN KEY (ID_TYPE)  REFERENCES SN_USER (ID_TYPE) 
);

CREATE TABLE TYPES_STYLES(
ID_STYLE	INT  AUTO_INCREMENT PRIMARY KEY, 
NAME 		VARCHAR(50) NOT NULL 

);

CREATE TABLE ARTISTIC_STYLE(
ID_ARTIST 	INT, 
ID_STYLE 	INT, 
PRIMARY KEY (ID_ARTIST,ID_STYLE),
FOREIGN KEY (ID_ARTIST) REFERENCES ARTIST(ID_ARTIST), 
FOREIGN KEY (ID_STYLE)  REFERENCES TYPES_STYLES(ID_STYLE)
);


CREATE TABLE SOCIAL_NETWORKS(
ID_TYPE_SN INT AUTO_INCREMENT PRIMARY KEY, 
NAME_SN VARCHAR(50)
);

CREATE TABLE SN_USER(
ID_TYPE INT ,
URL VARCHAR(255),
FOREIGN KEY (ID_TYPE) REFERENCES SOCIAL_NETWORKS(ID_TYPE)
);



CREATE TABLE EVENTOS(
    ID_EVENT          INT AUTO_INCREMENT PRIMARY KEY, 
    NAME_EVENT        VARCHAR(255) NOT NULL, 
    TYPE_EVENT_ID     INT, 
    START_DATE        DATE NOT NULL,
    END_DATE          DATE NOT NULL,
    START_TIME        TIME NOT NULL,
    END_TIME          TIME NOT NULL,
    ADDRESS           VARCHAR(255),
    PLACE             VARCHAR(255),
    COST              INT (10) DEFAULT NULL,
    PUBLIC_TYPE_ID    INT,
    DESCRIPTION_EVENT VARCHAR(500),
    FOREIGN KEY (TYPE_EVENT_ID) REFERENCES TYPE_EVENT(ID),
    FOREIGN KEY (PUBLIC_TYPE_ID) REFERENCES TYPE_PUBLIC(ID_PUBLIC)
);


CREATE TABLE TYPE_EVENT(
    ID            INT AUTO_INCREMENT PRIMARY KEY, 
    TYPE_EVENTO   ENUM('MUSEO', 'TALLER', 'EVENTO') NOT NULL DEFAULT 'TALLER'
);


CREATE TABLE TYPE_PUBLIC(
    ID_PUBLIC    INT AUTO_INCREMENT PRIMARY KEY,
    TYPE_PUBLIC    ENUM('apto para todo publico', '+ 18', 'niños y adolecentes') NOT NULL DEFAULT 'apto para todo publico'
);